# Generated by Django 3.2 on 2022-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salmi', '0002_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word_fr',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
